---
dependency:
  name: galaxy
  options:
    requirements-file: ././requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
